name: discourse
description: Discourse plugin development environment

# Habitat tests (run with: claude-habitat test discourse)
tests:
  - tests/test-discourse-setup.sh

# Use Discourse development base image (with ARG support)
base_image: discourse/discourse_dev:release

# Environment variables (discourse uses /discourse instead of default /workspace)
env:
  - USER=discourse
  - WORKDIR=/discourse
  - SYSTEM_PATH=/habitat/system
  - SHARED_PATH=/habitat/shared
  - LOCAL_PATH=/habitat/local
  - RAILS_ENV=test
  - RUBY_GLOBAL_METHOD_CACHE_SIZE=131072
  - LD_PRELOAD=/usr/lib/libjemalloc.so
  - CI=true
  - NO_EMBER_CLI=1
  - QUNIT_RAILS_ENV=test
  # GitHub App authentication

# Git repositories to clone
repos:
  - url: https://github.com/discourse/discourse
    path: /discourse
    branch: main
    shallow: true
    access: read  # Read-only dependency, not for active development

  # Plugins for active development
  - url: https://github.com/bitmage/county-fence-plugin
    path: /discourse/plugins/county-fence
    branch: main
    shallow: true
    access: write # (default) - Active development with PRs

  - url: https://github.com/bitmage/discourse-calendar
    path: /discourse/plugins/discourse-calendar
    branch: main
    shallow: true
    access: write # (default) - Active development with PRs

# Setup commands
scripts:
  # Setup commands migrated from Dockerfile
  - run_as: root
    commands:
      - |
        # Install basic tools needed for downloading and extracting static binaries
        apt update && apt install -y curl wget unzip
        apt clean && rm -rf /var/lib/apt/lists/*
  - run_as: root
    commands:
      - |
        # Wait for PostgreSQL
        echo "Waiting for PostgreSQL to be ready..."
        timeout 30 bash -c "while ! pg_isready -U postgres -q; do sleep 1; done"

        # Create test database
        sudo -u postgres createuser discourse 2>/dev/null || true
        sudo -u postgres createdb discourse_test -O discourse 2>/dev/null || true
  - run_as: discourse
    commands:
      - |
        cd /discourse
        echo "Installing Ruby dependencies..."
        bundle install

        echo "Installing JavaScript dependencies..."
        pnpm install

        echo "Setting up test database..."
        RAILS_ENV=test bin/rails db:create db:migrate

# Entry configuration (container runtime settings)
entry:
  command: claude --dangerously-skip-permissions
  init_command: /sbin/boot
  startup_delay: 10

# Filesystem verification structure
verify-fs:
  required_files:
    # Main discourse source files at project root
    - ${WORKDIR}/.git/config
    - ${WORKDIR}/Gemfile
    - ${WORKDIR}/package.json
    - ${WORKDIR}/bin/rails
    - ${WORKDIR}/app/controllers/application_controller.rb
    - ${WORKDIR}/plugins/county-fence
    - ${WORKDIR}/plugins/discourse-calendar
    # Infrastructure files in /habitat directories
    - ${SYSTEM_PATH}/config.yaml
    - ${SYSTEM_PATH}/tools/tools.yaml
    - ${SHARED_PATH}/config.yaml
    - ${LOCAL_PATH}/config.yaml
    # Note: CLAUDE.md files are excluded by .habignore but will be at /CLAUDE.md
