name: claude-habitat
description: Development environment for Claude Habitat itself

# Habitat tests (run with: claude-habitat test claude-habitat)
tests:
  - tests/test-claude-habitat-inception.sh

image:
  dockerfile: Dockerfile
  tag: claude-habitat-dev:latest

repositories:
  - url: https://github.com/bitmage/claude-habitat
    path: /workspace
    branch: main
    shallow: true

environment:
  - NODE_ENV=development
  - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  # Mount Docker socket for container management
  - /var/run/docker.sock:/var/run/docker.sock
  # Optional: Mount local code for live development
  # - ./:/workspace/claude-habitat

setup:
  root:
    - |
      # Fix Docker socket permissions for development
      chmod 666 /var/run/docker.sock || true

  user:
    run_as: node
    commands:
      - |
        cd /workspace
        echo "Installing Claude Habitat dependencies..."
        npm install
        echo "Running tests to verify setup..."
        npm test
        echo "Verifying Docker access..."
        /usr/bin/docker --version && echo "Docker CLI available" || echo "Docker not accessible"
        echo "Testing Docker socket..."
        /usr/bin/docker ps > /dev/null 2>&1 && echo "Docker socket accessible" || echo "Docker socket not accessible"
        echo "Claude Habitat setup complete"

container:
  work_dir: /workspace
  user: node
  init_command: /sbin/init
  startup_delay: 5

# Filesystem verification structure (bypass mode - just the repository)
verify-fs:
  required_files:
    # Main claude-habitat source files at repository root
    - /workspace/.git/config
    - /workspace/CLAUDE.md
    - /workspace/README.md
    - /workspace/package.json
    - /workspace/package-lock.json
    - /workspace/claude-habitat
    - /workspace/claude-habitat.js
    - /workspace/claude-habitat.sh
    - /workspace/habitats/base/config.yaml
    - /workspace/habitats/discourse/config.yaml
    - /workspace/test/unit/claude-habitat.test.js
    - /workspace/node_modules/package.json

# Bypass habitat infrastructure construction (claude-habitat is self-contained)
claude:
  command: claude --dangerously-skip-permissions
  bypass_habitat_construction: true
