name: claude-habitat
description: Development environment for Claude Habitat itself

# Habitat tests (run with: claude-habitat test claude-habitat)
# Temporarily disabled to test core functionality
# tests:
#   - tests/test-claude-habitat-inception.sh
#   - tests/test-tools-and-auth.sh

# Use Node.js base image instead of Dockerfile
base_image: node:20-bookworm

repositories:
  - url: https://github.com/bitmage/claude-habitat
    path: ${WORKDIR}
    branch: main
    shallow: true

env:
  - USER=node
  - HOME=/home/${USER}
  - WORKDIR=/workspace
  - HABITAT_PATH=${WORKDIR}
  - SYSTEM_PATH=${WORKDIR}/system
  - SHARED_PATH=${WORKDIR}/shared
  - LOCAL_PATH=${WORKDIR}/habitats/claude-habitat
  - SYSTEM_TOOLS_PATH=${SYSTEM_PATH}/tools/bin
  - SHARED_TOOLS_PATH=${SHARED_PATH}/tools/bin
  - LOCAL_TOOLS_PATH=${LOCAL_PATH}/tools/bin
  - PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:${SYSTEM_TOOLS_PATH}:${SHARED_TOOLS_PATH}:${LOCAL_TOOLS_PATH}
  - NODE_ENV=development
  - DOCKER_HOST=unix:///var/run/docker.sock
  - GITHUB_APP_ID=1357221
  - GITHUB_APP_PEM_FILE=${SHARED_PATH}/behold-the-power-of-claude.2025-06-04.private-key.pem

# Directory and file setup
files:
  # Copy system and shared directories for writable access
  - src: ./system
    dest: ${SYSTEM_PATH}
    after: repos
    owner: ${USER}
    description: "System tools and configuration (writable copy)"
  - src: ./shared
    dest: ${SHARED_PATH}
    after: repos
    owner: ${USER}
    description: "Shared configuration and resources (writable copy)"
  # Create .claude directory structure for Claude to use
  - src: /dev/null
    dest: ${HOME}/.claude/.keep
    mode: 644
    description: "Ensure .claude directory exists for Claude workspace"
  # Copy Claude credentials from host to container during build (bypass habitat only)
  - src: ~/.claude/.credentials.json
    dest: ~/.claude/.credentials.json
    mode: 600
    owner: ${USER}
    description: "Claude credentials for authentication"

volumes:
  # Mount Docker socket for container management
  - /var/run/docker.sock:/var/run/docker.sock

scripts:
  # Setup commands migrated from Dockerfile
  - run_as: root
    commands:
      - |
        # Accept build argument for docker group GID (default 999)
        DOCKER_GROUP_GID=${DOCKER_GROUP_GID:-999}
        
        # Install essential system dependencies including Docker
        apt-get update && apt-get install -y \
          vim \
          curl \
          git \
          sudo \
          wget \
          ca-certificates \
          gnupg \
          lsb-release \
          && rm -rf /var/lib/apt/lists/*
        
        # Install Docker CE
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
        apt-get update
        apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
        rm -rf /var/lib/apt/lists/*
        groupdel docker || true
        
        # Install Claude Code globally
        npm install -g @anthropic-ai/claude-code
        
        # Use existing node user (UID 1000) and give it sudo access
        echo "node ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
        
        # Add node user to docker group (create group if it doesn't exist)
        (getent group docker >/dev/null 2>&1 && echo "Docker group exists") || \
          (groupadd -g ${DOCKER_GROUP_GID} docker && echo "Created docker group")
        (usermod -aG docker node && echo "Added node to docker group") || \
          echo "Warning: Could not add node to docker group, will run without Docker access"
        
        # Create workspace directory structure with proper permissions
        mkdir -p /workspace
        chown -R node:node /workspace
        mkdir -p /home/node/.claude
        chown -R node:node /home/node/.claude
        chmod 755 /home/node/.claude

  - run_as: node
    commands:
      - |
        set -e  # Exit on any error

        ${SYSTEM_PATH}/tools/bin/install-gitconfig
        ${SYSTEM_PATH}/tools/bin/setup-github-auth

  - run_as: node
    after: repos
    commands:
      - |
        set -e  # Exit on any error

        echo "Running npm install..."
        npm install

container:
  startup_delay: 5

# Filesystem verification structure (bypass mode - Meta Claude structure)
# Temporarily disabled problematic git config verification during file hooks testing
verify-fs:
  required_files:
    # Main claude-habitat source files at repository root
    - "${WORKDIR}/.git/config"
    - "${WORKDIR}/CLAUDE.md"
    - "${WORKDIR}/README.md"
    - "${WORKDIR}/package.json"
    - "${WORKDIR}/package-lock.json"
    - "${WORKDIR}/claude-habitat"
    - "${WORKDIR}/claude-habitat.js"
    - "${WORKDIR}/habitats/base/config.yaml"
    - "${WORKDIR}/habitats/discourse/config.yaml"
    - "${WORKDIR}/test/unit/claude-habitat.test.js"
    # Node modules verification (check key directories exist)
    - "${WORKDIR}/node_modules"
    - "${WORKDIR}/node_modules/js-yaml"
    # System infrastructure (excluding .md files which are filtered by .habignore)
    - "${SYSTEM_PATH}/config.yaml"
    - "${SYSTEM_PATH}/tools/install-tools.sh"
    - "${SYSTEM_PATH}/tools/regenerate-github-token.sh"
    - "${SYSTEM_PATH}/tools/tools.yaml"
    # Installed system tools
    - "${SYSTEM_PATH}/tools/bin/setup-github-auth"
    - "${SYSTEM_PATH}/tools/bin/rg"
    - "${SYSTEM_PATH}/tools/bin/fd"
    - "${SYSTEM_PATH}/tools/bin/jq"
    - "${SYSTEM_PATH}/tools/bin/yq"
    - "${SYSTEM_PATH}/tools/bin/gh"
    - "${SYSTEM_PATH}/tools/bin/eza"
    - "${SYSTEM_PATH}/tools/bin/bat"
    - "${SYSTEM_PATH}/tools/bin/install-gitconfig"
    - "${SYSTEM_PATH}/tools/tap-helpers.sh"
    # Shared directory structure
    - "${SHARED_PATH}/config.yaml"
    - "${SHARED_PATH}/gitconfig"
    - "${SHARED_PATH}/behold-the-power-of-claude.2025-06-04.private-key.pem"
    # user files
    - ~/.gitconfig
    - ~/.claude/.credentials.json

# Bypass habitat infrastructure construction (claude-habitat is self-contained)
claude:
  command: claude --dangerously-skip-permissions
  tty: true  # Enable TTY for proper Claude output display (default: true)
  bypass_habitat_construction: true
