name: claude-habitat
description: Development environment for Claude Habitat itself

# Habitat tests (run with: claude-habitat test claude-habitat)
tests:
  - tests/test-claude-habitat-inception.sh

image:
  dockerfile: habitats/claude-habitat/Dockerfile
  tag: claude-habitat-claude-habitat:latest

repositories:
  - url: https://github.com/bitmage/claude-habitat
    path: /workspace
    branch: main
    shallow: true

environment:
  - WORKDIR=/workspace
  - HABITAT_PATH=${WORKDIR}/claude-habitat
  - SYSTEM_PATH=${HABITAT_PATH}/system
  - SHARED_PATH=${HABITAT_PATH}/shared
  - LOCAL_PATH=${HABITAT_PATH}/local
  - SYSTEM_TOOLS_PATH=${SYSTEM_PATH}/tools/bin
  - SHARED_TOOLS_PATH=${SHARED_PATH}/tools/bin
  - LOCAL_TOOLS_PATH=${LOCAL_PATH}/tools/bin
  - PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin:${SYSTEM_TOOLS_PATH}:${SHARED_TOOLS_PATH}:${LOCAL_TOOLS_PATH}
  - NODE_ENV=development
  - DOCKER_HOST=unix:///var/run/docker.sock

# Directory and file setup
files:
  # Create .claude directory structure for Claude to use
  - src: /dev/null
    dest: /home/{container.user}/.claude/.keep
    mode: 644
    description: "Ensure .claude directory exists for Claude workspace"
  # Copy Claude credentials from host to container during build (bypass habitat only)
  - src: ~/.claude/.credentials.json
    dest: /home/{container.user}/.claude/.credentials.json
    mode: 600
    owner: "{container.user}"
    description: "Claude credentials for authentication"

volumes:
  # Mount Docker socket for container management
  - /var/run/docker.sock:/var/run/docker.sock
  # Optional: Mount local code for live development
  # - ./:/workspace/claude-habitat

setup:
  root:
    - |
      # Fix Docker socket permissions for development
      chmod 666 /var/run/docker.sock || true

      # Ensure .claude directory exists and has proper ownership for node user
      # Create this BEFORE any volumes are mounted to avoid ownership conflicts
      mkdir -p /home/node/.claude
      chown node:node /home/node/.claude
      chmod 755 /home/node/.claude
      echo "Created .claude directory with node ownership"

  user:
    run_as: node
    commands:
      - |
        cd /workspace
        echo "Installing Claude Habitat dependencies..."
        npm install
        echo "Running tests to verify setup..."
        npm test
        echo "Verifying Docker access..."
        /usr/bin/docker --version && echo "Docker CLI available" || echo "Docker not accessible"
        echo "Testing Docker socket..."
        /usr/bin/docker ps > /dev/null 2>&1 && echo "Docker socket accessible" || echo "Docker socket not accessible"

        # Ensure .claude directory has proper permissions (credentials copied by system setup)
        mkdir -p ~/.claude
        chmod 755 ~/.claude
        echo "Claude directory permissions set for user: $(whoami)"
        ls -la ~/.claude

        # Set up GitHub App authentication using system tools (Meta Claude's structure)
        echo "Setting up GitHub authentication..."
        "{env.WORKDIR}/system/tools/bin/setup-github-auth"
        
        # Configure git for container user using centralized script
        echo "Setting up git configuration..."
        "{env.SYSTEM_PATH}/tools/bin/install-gitconfig"

        echo "Claude Habitat setup complete"

container:
  user: node
  init_command: /usr/local/bin/habitat-init
  startup_delay: 5

# Filesystem verification structure (bypass mode - Meta Claude structure)
verify-fs:
  required_files:
    # Main claude-habitat source files at repository root
    - "${WORKDIR}/.git/config"
    - "${WORKDIR}/CLAUDE.md"
    - "${WORKDIR}/README.md"
    - "${WORKDIR}/package.json"
    - "${WORKDIR}/package-lock.json"
    - "${WORKDIR}/claude-habitat"
    - "${WORKDIR}/claude-habitat.js"
    - "${WORKDIR}/claude-habitat.sh"
    - "${WORKDIR}/habitats/base/config.yaml"
    - "${WORKDIR}/habitats/discourse/config.yaml"
    - "${WORKDIR}/test/unit/claude-habitat.test.js"
    - "${WORKDIR}/node_modules/package.json"
    # System tools (Meta Claude's structure)
    - "${WORKDIR}/system/tools/bin/setup-github-auth"
    - "${WORKDIR}/system/tools/bin/rg"
    - "${WORKDIR}/system/tools/bin/fd"
    - "${WORKDIR}/system/tools/bin/jq"
    - "${WORKDIR}/system/tools/bin/yq"
    - "${WORKDIR}/system/tools/bin/gh"
    - "${WORKDIR}/system/tools/install-tools.sh"
    - "${WORKDIR}/system/tools/regenerate-github-token.sh"
    - "${WORKDIR}/system/tools/tools.yaml"
    # Claude workspace directory (created by files section)
    - ~/.claude/.keep
    # Claude credentials (copied from host)
    - ~/.claude/.credentials.json

# Bypass habitat infrastructure construction (claude-habitat is self-contained)
claude:
  command: claude --dangerously-skip-permissions
  tty: true  # Enable TTY for proper Claude output display (default: true)
  bypass_habitat_construction: true
