# System infrastructure configuration applied to all habitats
name: system-setup  
description: Core infrastructure setup for all claude-habitat containers

# System tests (run with: claude-habitat test --system)
tests:
  - tests/test-core-tools.sh
  - tests/test-file-operations.sh
  - tests/test-git-auth.sh

# System-level file operations
files:
  # Future examples:
  # - src: bashrc-additions
  #   dest: /etc/bash.bashrc.d/claude-habitat
  #   mode: 644
  #   description: "System bash configuration additions"

# System setup commands
setup:
  root:
    - |
      # System-wide configuration
      echo "Claude Habitat system setup complete"
      
      # Ensure profile.d directory exists for future use
      mkdir -p /etc/profile.d
      
      # Set timezone if not already set
      if [ ! -f /etc/timezone ]; then
        echo "UTC" > /etc/timezone
      fi

  user:
    run_as: "{container_user}"  
    commands:
      - |
        # Set up GitHub App authentication using tools
        echo "Debug: Current directory: $(pwd)"
        echo "Debug: Available files: $(ls -la . 2>/dev/null || echo 'none')"
        echo "Debug: Checking for tools..."
        
        if [ -x "./habitat/system/tools/bin/setup-github-auth" ]; then
          echo "✅ Found tool at ./habitat/system/tools/bin/setup-github-auth"
          echo "Setting up GitHub authentication..."
          ./habitat/system/tools/bin/setup-github-auth
        elif [ -x "./claude-habitat/system/tools/bin/setup-github-auth" ]; then
          echo "✅ Found tool at ./claude-habitat/system/tools/bin/setup-github-auth"
          echo "Setting up GitHub authentication..."
          ./claude-habitat/system/tools/bin/setup-github-auth
        elif [ -x "./system/tools/bin/setup-github-auth" ]; then
          echo "✅ Found tool at ./system/tools/bin/setup-github-auth"
          echo "Setting up GitHub authentication..."
          ./system/tools/bin/setup-github-auth
        else
          echo "❌ GitHub auth setup tool not found"
          echo "Debug: Checked paths:"
          echo "  ./habitat/system/tools/bin/setup-github-auth (exists: $([ -f './habitat/system/tools/bin/setup-github-auth' ] && echo yes || echo no), executable: $([ -x './habitat/system/tools/bin/setup-github-auth' ] && echo yes || echo no))"
          echo "  ./claude-habitat/system/tools/bin/setup-github-auth (exists: $([ -f './claude-habitat/system/tools/bin/setup-github-auth' ] && echo yes || echo no), executable: $([ -x './claude-habitat/system/tools/bin/setup-github-auth' ] && echo yes || echo no))"
          echo "  ./system/tools/bin/setup-github-auth (exists: $([ -f './system/tools/bin/setup-github-auth' ] && echo yes || echo no), executable: $([ -x './system/tools/bin/setup-github-auth' ] && echo yes || echo no))"
          echo "⚠️  Skipping authentication setup"
        fi