# System infrastructure configuration applied to all habitats
name: system-setup
description: Core infrastructure setup for all claude-habitat containers

# Default environment variables (can be overridden by shared/habitat configs)
env:
  - USER=root
  - WORKDIR=/workspace
  - HABITAT_PATH=${WORKDIR}/habitat
  - SYSTEM_PATH=${HABITAT_PATH}/system
  - SHARED_PATH=${HABITAT_PATH}/shared
  - LOCAL_PATH=${HABITAT_PATH}/local
  - SYSTEM_TOOLS_PATH=${SYSTEM_PATH}/tools/bin
  - PATH=${PATH}:${SYSTEM_TOOLS_PATH}

# System-wide volume mounts applied to all habitats
# volumes:
  # Claude credentials are now copied during build instead of mounted

# System tests (run with: claude-habitat test --system)
tests:
  - tests/test-core-tools.sh
  - tests/test-file-operations.sh
  - tests/test-git-auth.sh

# System-level file operations
files:
  # Copy Claude credentials from host to container during build
  - src: ~/.claude/.credentials.json
    dest: ~/.claude/.credentials.json
    mode: 600
    owner: "{env.USER}"
    description: "Claude credentials for authentication"
  # Future examples:
  # - src: bashrc-additions
  #   dest: /etc/bash.bashrc.d/claude-habitat
  #   mode: 644
  #   description: "System bash configuration additions"

# System setup commands
setup:
  root:
    - |
      # System-wide configuration
      echo "Claude Habitat system setup complete"

      # Ensure profile.d directory exists for future use
      mkdir -p /etc/profile.d

      # Set timezone if not already set
      if [ ! -f /etc/timezone ]; then
        echo "UTC" > /etc/timezone
      fi

  user:
    run_as: "{env.USER}"
    commands:
      - |
        # Set up GitHub App authentication using tools
        echo "Setting up GitHub authentication..."
        "{env.SYSTEM_PATH}/tools/bin/setup-github-auth"

# Filesystem verification structure
verify-fs:
  required_files:
    # Core system tools
    - "${SYSTEM_PATH}/tools/bin/setup-github-auth"
    - "${SYSTEM_PATH}/tools/bin/rg"
    - "${SYSTEM_PATH}/tools/bin/fd"
    - "${SYSTEM_PATH}/tools/bin/jq"
    - "${SYSTEM_PATH}/tools/bin/yq"
    - "${SYSTEM_PATH}/tools/bin/gh"
    - "${SYSTEM_PATH}/tools/install-tools.sh"
    - "${SYSTEM_PATH}/tools/regenerate-github-token.sh"
    - "${SYSTEM_PATH}/tools/tools.yaml"
    # Claude credentials (copied from host during build)
    - ~/.claude/.credentials.json
