# System infrastructure configuration applied to all habitats
name: system-setup  
description: Core infrastructure setup for all claude-habitat containers

# Container settings for system setup
container:
  work_dir: /workspace
  user: root

# System-wide volume mounts applied to all habitats
# volumes:
  # Claude credentials are now copied during build instead of mounted

# System tests (run with: claude-habitat test --system)
tests:
  - tests/test-core-tools.sh
  - tests/test-file-operations.sh
  - tests/test-git-auth.sh

# System-level file operations
files:
  # Copy Claude credentials from host to container during build
  - src: ~/.claude/.credentials.json
    dest: ~/.claude/.credentials.json
    mode: 600
    owner: "{container.user}"
    description: "Claude credentials for authentication"
  # Future examples:
  # - src: bashrc-additions
  #   dest: /etc/bash.bashrc.d/claude-habitat
  #   mode: 644
  #   description: "System bash configuration additions"

# System setup commands
setup:
  root:
    - |
      # System-wide configuration
      echo "Claude Habitat system setup complete"
      
      # Ensure profile.d directory exists for future use
      mkdir -p /etc/profile.d
      
      # Set timezone if not already set
      if [ ! -f /etc/timezone ]; then
        echo "UTC" > /etc/timezone
      fi

  user:
    run_as: "{container.user}"
    commands:
      - |
        # Set up GitHub App authentication using tools
        echo "Setting up GitHub authentication..."
        ${work_dir}/claude-habitat/system/tools/bin/setup-github-auth

# Filesystem verification structure
verify-fs:
  required_files:
    # Core system tools
    - ./habitat/system/tools/bin/setup-github-auth
    - ./habitat/system/tools/bin/rg
    - ./habitat/system/tools/bin/fd
    - ./habitat/system/tools/bin/jq
    - ./habitat/system/tools/bin/yq
    - ./habitat/system/tools/bin/gh
    - ./habitat/system/tools/install-tools.sh
    - ./habitat/system/tools/regenerate-github-token.sh
    - ./habitat/system/tools/tools.yaml
    # Claude credentials (copied from host during build)
    - ~/.claude/.credentials.json