# System infrastructure configuration applied to all habitats
name: system-setup
description: Core infrastructure setup for all claude-habitat containers

# Default environment variables (can be overridden by shared/habitat configs)
env:
  - USER=root
  - WORKDIR=/workspace
  - SYSTEM_PATH=/habitat/system
  - SHARED_PATH=/habitat/shared
  - SHARED_TOOLS_PATH=${SHARED_PATH}/tools/bin
  - LOCAL_PATH=/habitat/local
  - SYSTEM_TOOLS_PATH=${SYSTEM_PATH}/tools/bin
  - PATH=${PATH}:${SYSTEM_TOOLS_PATH}:${SHARED_TOOLS_PATH}

# Container settings for system setup
container: {}

# System-wide volume mounts applied to all habitats
# volumes:
  # Claude credentials are now copied during build instead of mounted

# System tests (run with: claude-habitat test --system)
tests:
  - tests/test-core-tools.sh
  - tests/test-file-operations.sh
  - tests/test-git-auth.sh

# System-level file operations
files:
  # Copy Claude directory to root for Claude to find
  - src: ~/.claude
    dest: /.claude
    owner: ${USER}
    description: "Claude configuration and credentials"
  # Copy system CLAUDE.md to root
  - src: ./system/CLAUDE.md
    dest: /CLAUDE.md
    mode: 644
    description: "Claude instructions at root"

# System setup commands
scripts:
  - run_as: root
    commands:
      - |
        # Create /habitat directory structure
        echo "Creating /habitat directory structure..."
        mkdir -p /habitat
        chown ${USER}:${USER} /habitat
        chmod 755 /habitat
  - run_as: root
    commands:
      - |
        # System-wide configuration
        echo "Claude Habitat system setup complete"

        # Ensure profile.d directory exists for future use
        mkdir -p /etc/profile.d

        # Set timezone if not already set
        if [ ! -f /etc/timezone ]; then
          echo "UTC" > /etc/timezone
        fi

  - run_as: ${USER}
    commands:
      - |
        # Set up GitHub App authentication using tools
        echo "Setting up GitHub authentication..."
        ${SYSTEM_PATH}/tools/bin/setup-github-auth

# Filesystem verification structure
verify-fs:
  required_files:
    # Core system tools
    - "${SYSTEM_PATH}/tools/bin/setup-github-auth"
    - "${SYSTEM_PATH}/tools/bin/rg"
    - "${SYSTEM_PATH}/tools/bin/fd"
    - "${SYSTEM_PATH}/tools/bin/jq"
    - "${SYSTEM_PATH}/tools/bin/yq"
    - "${SYSTEM_PATH}/tools/bin/gh"
    - "${SYSTEM_PATH}/tools/install-tools.sh"
    - "${SYSTEM_PATH}/tools/regenerate-github-token.sh"
    - "${SYSTEM_PATH}/tools/tools.yaml"
    # Claude files at root
    - /.claude
    - /CLAUDE.md
