name: base
description: Minimal base habitat for testing system and shared components

# Docker image configuration
image:
  dockerfile: habitats/base/Dockerfile
  tag: claude-habitat-base:latest

# No repositories needed for base habitat
repositories: []

# Environment configuration (inherits from system, sets explicit WORKDIR for base habitat)
env:
  - USER=root
  - WORKDIR=/workspace

# No additional setup needed
setup: {}

# Container configuration
container:
  init_command: /sbin/init
  startup_delay: 2

# Claude configuration
claude:
  command: claude --dangerously-skip-permissions
