# Shared user configuration applied to all habitats
name: shared-setup
description: User preferences and shared configuration for all habitats

# Shared tests (run with: claude-habitat test --shared)
tests:
  - tests/test-user-config.sh

# Shared environment variables (add to system PATH)
env:
  - SHARED_TOOLS_PATH=${SHARED_PATH}/tools/bin
  - PATH=${PATH}:${SHARED_TOOLS_PATH}

# Structured file operations - copy files to specific locations with permissions
files:
  - src: gitconfig
    dest: /etc/gitconfig
    mode: 644
    description: "System-wide git configuration"
    
  - src: gitconfig  
    dest: /root/.gitconfig
    mode: 644
    description: "Git configuration for root user"
    
  # Future example: user aliases
  # - src: aliases.sh
  #   dest: /etc/profile.d/user-aliases.sh
  #   mode: 755
  #   description: "User command aliases"

# Setup commands that run after file operations
setup:
  user:
    run_as: "{container.user}"
    commands:
      - |
        # Configure git for container user using centralized script
        "{env.SYSTEM_PATH}/tools/bin/install-gitconfig"

# Filesystem verification - verify shared/user files are properly configured
verify-fs:
  required_files:
    # Git configuration files
    - /etc/gitconfig
    - /root/.gitconfig
    # Infrastructure files
    - "{env.SHARED_PATH}/CLAUDE.md"
    - "{env.SHARED_PATH}/config.yaml"
    - "{env.SHARED_PATH}/gitconfig"