# Shared user configuration applied to all habitats
name: shared-setup
description: User preferences and shared configuration for all habitats

# Shared tests (run with: claude-habitat test --shared)
tests:
  - tests/test-user-config.sh

# Structured file operations - copy files to specific locations with permissions
files:
  - src: gitconfig
    dest: /etc/gitconfig
    mode: 644
    description: "System-wide git configuration"
    
  - src: gitconfig  
    dest: /root/.gitconfig
    mode: 644
    description: "Git configuration for root user"
    
  # Future example: user aliases
  # - src: aliases.sh
  #   dest: /etc/profile.d/user-aliases.sh
  #   mode: 755
  #   description: "User command aliases"

# Setup commands that run after file operations
setup:
  user:
    run_as: "{container.user}"
    commands:
      - |
        # Configure git for container user
        if [ -f "{env.SHARED_PATH}/gitconfig" ]; then
          cp "{env.SHARED_PATH}/gitconfig" ~/.gitconfig
          chmod 644 ~/.gitconfig
          echo "Git configuration applied for user: $(whoami)"
        fi

# Filesystem verification - verify shared/user files are properly configured
verify-fs:
  required_files:
    # Git configuration files
    - /etc/gitconfig
    - /root/.gitconfig
    # Infrastructure files
    - "{env.SHARED_PATH}/CLAUDE.md"
    - "{env.SHARED_PATH}/config.yaml"
    - "{env.SHARED_PATH}/gitconfig"